import { Newspaper } from "lucide-react";
import { PlaceholderPage } from "@/components/PlaceholderPage";

export default function NewsPage() {
  return (
    <PlaceholderPage
      icon={Newspaper}
      title="News"
      description="Curated feed from RSS sources plus everything caught by the Gmail ai-news label — deduped on (source, source_ref) to keep noise down."
      phase="Phase 3"
      upcoming={[
        "Star + read state with daily auto-archive",
        "Tag filters and source toggles",
        "Inline summary generated by claude-sonnet-4-6",
        "Send-to-task / send-to-reading-queue actions",
      ]}
    />
  );
}
